#!/bin/bash

# Vercel Environment Variables Setup for OAuth Deployment
echo "Setting up Vercel environment variables for production deployment..."

# Production OAuth callback URLs that need to be configured:
PRODUCTION_URL="https://upcode-coding-and-interview-platfor.vercel.app"
GOOGLE_CALLBACK="${PRODUCTION_URL}/api/auth/callback/google"
GITHUB_CALLBACK="${PRODUCTION_URL}/api/auth/callback/github"

echo "=== REQUIRED OAUTH APP CONFIGURATIONS ==="
echo ""
echo "🔧 GOOGLE OAUTH APP SETTINGS:"
echo "   Console: https://console.cloud.google.com/apis/credentials"
echo "   Client ID: 573233104808-gbe71vve36vrhotmqj8svtnn9jr4pgeh.apps.googleusercontent.com"
echo "   Authorized redirect URIs (ADD THESE):"
echo "   - ${GOOGLE_CALLBACK}"
echo "   - http://localhost:3000/api/auth/callback/google (for development)"
echo ""
echo "🔧 GITHUB OAUTH APP SETTINGS:"
echo "   Console: https://github.com/settings/developers"
echo "   Client ID: Ov23li7uoBwSBvON0mS1" 
echo "   Authorization callback URL (CHANGE TO):"
echo "   - ${GITHUB_CALLBACK}"
echo "   - http://localhost:3000/api/auth/callback/github (for development)"
echo ""

echo "=== VERCEL ENVIRONMENT VARIABLES TO SET ==="
echo ""
echo "Run these commands in your Vercel CLI or add via Vercel dashboard:"
echo ""

# Read environment variables from .env.local
echo "vercel env add NEXTAUTH_SECRET"
echo "vercel env add NEXTAUTH_URL"
echo "vercel env add GOOGLE_CLIENT_ID"
echo "vercel env add GOOGLE_CLIENT_SECRET"
echo "vercel env add GITHUB_ID"
echo "vercel env add GITHUB_SECRET"
echo "vercel env add MONGODB_URI"
echo "vercel env add RAZORPAY_KEY_ID"
echo "vercel env add RAZORPAY_KEY_SECRET"
echo "vercel env add NEXT_PUBLIC_RAZORPAY_KEY_ID"
echo "vercel env add GEMINI_API_KEY"
echo "vercel env add SENDGRID_API_KEY"
echo "vercel env add SENDGRID_FROM_EMAIL"
echo "vercel env add EMAIL_FROM"
echo ""

echo "=== AUTOMATIC VERCEL ENV SETUP ==="
echo "Alternatively, you can set them automatically:"
echo ""
echo "# Production values"
echo "vercel env add NEXTAUTH_URL production <<< '${PRODUCTION_URL}'"
echo "vercel env add NODE_ENV production <<< 'production'"
echo "vercel env add NEXTAUTH_DEBUG production <<< 'false'"
echo ""

echo "=== DEPLOYMENT CHECKLIST ==="
echo ""
echo "✅ Update OAuth app callback URLs in Google/GitHub consoles"
echo "✅ Set Vercel environment variables"
echo "✅ Test OAuth flows after deployment"
echo "✅ Monitor deployment logs for any errors"
echo ""

echo "=== TESTING AFTER DEPLOYMENT ==="
echo ""
echo "1. Visit: ${PRODUCTION_URL}/login"
echo "2. Test Google OAuth authentication"
echo "3. Test GitHub OAuth authentication"
echo "4. Check browser console for any errors"
echo "5. Verify user sessions are created properly"
echo ""

echo "Script completed. Please follow the steps above before deploying!"
